export const STAGES = [
  "LEAD_IN",
  "BID_SCHEDULED",
  "DESIGN_FEE",
  "BID_GIVEN",
  "WON",
  "LOST",
  "CONTRACT_SENT",
  "CONTRACT_SIGNED",
  "DEPOSIT_INVOICED",
  "DEPOSIT_PAID",
  "JOB_SCHEDULED",
  "IN_PROGRESS",
  "FINAL_INVOICE_SENT",
  "FINAL_PAYMENT_RECEIVED",
  "COMPLETE",
];

const TRANSITIONS = {
  LEAD_IN: ["BID_SCHEDULED"],
  BID_SCHEDULED: ["DESIGN_FEE", "BID_GIVEN"],
  DESIGN_FEE: ["BID_GIVEN"],
  BID_GIVEN: ["WON", "LOST"],
  WON: ["CONTRACT_SENT"],
  LOST: [],
  CONTRACT_SENT: ["CONTRACT_SIGNED"],
  CONTRACT_SIGNED: ["DEPOSIT_INVOICED"],
  DEPOSIT_INVOICED: ["DEPOSIT_PAID"],
  DEPOSIT_PAID: ["JOB_SCHEDULED"],
  JOB_SCHEDULED: ["IN_PROGRESS"],
  IN_PROGRESS: ["FINAL_INVOICE_SENT"],
  FINAL_INVOICE_SENT: ["FINAL_PAYMENT_RECEIVED"],
  FINAL_PAYMENT_RECEIVED: ["COMPLETE"],
  COMPLETE: [],
};

export function canTransition(from, to) {
  return Object.hasOwn(TRANSITIONS, from) && TRANSITIONS[from].includes(to);
}

const MANUALLY_EXCLUDED_TRANSITIONS = new Set(["WON:CONTRACT_SENT", "CONTRACT_SENT:CONTRACT_SIGNED"]);

export function canManuallyTransition(from, to) {
  return canTransition(from, to) && !MANUALLY_EXCLUDED_TRANSITIONS.has(`${from}:${to}`);
}
